#index:
#    path: /
#    controller: App\Controller\DefaultController::index
presentation:
    path: /presentation
    controller: 'App\Controller\PresentationController::index'
register:
    path: /register
    controller: 'App\Controller\RegistrationController::index'
login:
    path: /login
    controller: 'App\Controller\AuthenticatorController::index'
