#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
    path: /register
    controller: 'App\Controller\RegistrationController::index'
login:
    path: /login
    controller: 'App\Controller\AuthenticatorController::index'
presentation:
    path: /presentation
    controller: 'App\Controller\PresentationController::index'
app_presentation:
    resource: ../src/Controller/PresentationController.php
    prefix: /
    type: annotation
app_contact_liste:
    resource: ../src/Controller/ContactController.php
    prefix: /
    type: annotation